# Generated by Django 5.1.6 on 2025-08-26 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_learningcategory_learningmaterial_learningprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='learning/images/'),
        ),
        migrations.CreateModel(
            name='CHPProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('facility_assigned', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referrals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('symptoms', models.TextField()),
                ('referral_type', models.CharField(choices=[('urgent', 'Urgent Referral'), ('routine', 'Routine Referral')], max_length=10)),
                ('facility', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.chpprofile')),
            ],
        ),
    ]
